language: php

php:
  - 7.1
  
before_script:
  - travis encrypt 'GITHUB_TOKEN=<dfcfc94a48063fd877316636903f31bed301236f>'
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/tester -s -p php tests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
