language: php

php:
  - 7.1
  - hhvm
  
env:
  - NETTE=default
  - NETTE=~2.4.0

matrix:
  allow_failures:
    - php: hhvm
      
before_script:
  - composer self-updateinstall:
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/tester -s -p php tests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
