language: php

php:
  - 7.1

before_script:
  - composer self-updateinstall:

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/tester -s -p php tests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
