language: php

php:
  - 7.1
  
before_script:
  - travis_retry composer self-update ~1.3.0
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/tester -s -p php tests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
